openapi: 3.0.0
info:
  version: 1.0.0
  title: Neoflex tutorial
  description: Tutorial from NodeJS curse
  contact:
    name: Pastuh
    url: https://github.com/pastuh12
servers:
      - url: http://localhost:8080
paths:
    /student:
      get:
        description: Get student
        parameters:
          - name: name
            in: query
            required: true
            schema:
              type: string
              example: Ilya
        responses:
          '200':
            description: Successful Response
            content:
              application/json:
                schema:
                  type: array
                  items:
                    properties:
                      StudentId:
                        type: string
                        example: High Grade Student
          